[workspace]
resolver = "3"
members = ["kernel", "model", "view", "view_model"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[workspace.dependencies]
eframe = { version = "0.36.2", default-features = false, features = ["default_fonts", "glow", "x11", "wayland", "persistence"] }
egui_extras = { version = "0.36.2", features = ["svg"] }
view_model = { path = "view_model" }
view = { path = "view" }
model = { path = "model" }
rstest = "0.27.0"
usvg = "0.48.1"
egui_kittest = "0.36.2"
chrono = { version = "0.4.45", default-features = false, features = ["clock", "std"] }
rfd = "0.17.2"
pollster = "1.0.1"
sor-rs = { git = "https://github.com/WolfMTK/sor-rs" }
serde = {version = "1.0.229", features = ["derive"]}
