[package]
name = "view"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
eframe.workspace = true
egui_extras.workspace = true
view_model.workspace = true
model.workspace = true
rfd.workspace = true
pollster.workspace = true

[dev-dependencies]
rstest.workspace = true
usvg.workspace = true
egui_kittest.workspace = true
